language: node_js
node_js:
  - 10
  - 9
  - 8

cache: npm

install:
  - npm install

jobs:
  include:
    - stage: Compilation
      script: npm run compile
    - stage: Markdown Linting
      script: npm run lint
