name: CI

on: [push, pull_request]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: "10.x"
      - name: Install dependencies
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Run Webpack
        run: npm run webpack
      - name: VSCE package
        run: npx vsce package
